name: safenote-infrastructure
services:
  - name: db
    image: postgres:15-alpine
    bindings:
      - port: 5432
    env:
      - name: POSTGRES_DB
        value: safenote.db
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: mysecretpassword
